using UnityEngine;
using UnityEngine.UI;

public class UserChoice : MonoBehaviour
{
    public Text display;
    private Demigod user;
    private string d = "";
    private string s = "";
    private string g = "";
    private int a;
    public GameObject AthenaS, AthenaD, AphroditeS, AphroditeD, AresS, AresD;
    public GameObject ApolloS, ApolloD, ArtemisS, ArtemisD, DionysusS, DionysusD;
    public GameObject DemeterS, DemeterD, HermesS, HermesD, HephaestusS, HephaestusD;
    public GameObject ZeusS, ZeusD, PoseidonS, PoseidonD, HadesS, HadesD, HeraS, HeraD;
    public static int story;
    public static int character;

    void Awake()
    {
        user=GameObject.FindObjectOfType<Demigod>();
    }
    public void Gender(int x)
    {
        if(x==1)
            s="Son of ";
        else if(x==2)
            s="Daughter of ";

        if(g.Equals("Artemis")&&x==1)
            s="Friend of ";
        else if(g.Equals("Artemis")&&x==2)
            s="Hunter of ";
        else if(g.Equals("Hera"))
        {
            s="Pawn of ";
        }
        a=x;
    }
    
    public void God(int x)
    {
        switch(x)
        {
            case 1:
                g ="Aphrodite";
                break;
            case 2:
                g ="Ares";
                break;
            case 3:
                g ="Apollo";
                break;
            case 4:
                g ="Artemis";
                break;
            case 5:
                g ="Dionysus";
                break;
            case 6:
                g ="Hephaestus";
                break;
            case 7:
                g ="Hermes";
                break;
            case 8:
                g ="Athena";
                break;
            case 9:
                g ="Demeter";
                break;
            case 10:
                g ="Hera";
                break;
            case 11:
                g ="Zeus";
                break;
            case 12:
                g ="Poseidon";
                break;
            case 13:
                g ="Hades";
                break;
        }
    }

    public void Display()
    {
        d=s+g;
        display.text=d.ToString();
    }
    public void Transfer()
    {
        //user.AssignGod(g);
        //user.AssignGender(a);
        if(g.Equals("Dionysus")&&a==1)
        {
            character=14;
            story=7;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false); 
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(true);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Dionysus")&&a==2)
        {
            character=13;
            story=7;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(true);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Ares")&&a==1)
        {
            character=4;
            story=2;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(true);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Ares")&&a==2)
        {
            character=3;
            story=2;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(true);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Artemis")&&a==1)
        {
            character=8;
            story=4;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(true);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Artemis")&&a==2)
        {
            character=7;
            story=4;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(true);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Apollo")&&a==1)
        {
            character=6;
            story=3;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(true);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Apollo")&&a==2)
        {
            character=5;
            story=3;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(true);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Aphrodite")&&a==1)
        {
            character=10;
            story=5;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(true);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Aphrodite")&&a==2)
        {
            character=9;
            story=5;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(true);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Athena")&&a==1)
        {
            character=2;
            story=1;
            AthenaD.SetActive(false);
            AthenaS.SetActive(true);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Athena")&&a==2)
        {
            character=1;
            story=1;
            AthenaD.SetActive(true);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Zeus")&&a==1)
        {
            character=26;
            story=13;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(true);
        }
        else if(g.Equals("Zeus")&&a==2)
        {
            character=25;
            story=13;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(true);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Hades")&&a==1)
        {
            character=22;
            story=11;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(true);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Hades")&&a==2)
        {
            character=21;
            story=11;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(true);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Hera")&&a==1)
        {
            character=18;
            story=9;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(true);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Hera")&&a==2)
        {
            character=17;
            story=9;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(true);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Hermes")&&a==1)
        {
            character=16;
            story=8;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(true);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Hermes")&&a==2)
        {
            character=15;
            story=8;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(true);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Hephaestus")&&a==1)
        {
            character=20;
            story=10;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(true);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Hephaestus")&&a==2)
        {
            character=19;
            story=10;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(true);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Demeter")&&a==1)
        {
            character=12;
            story=6;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(true);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Demeter")&&a==2)
        {
            character=11;
            story=6;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(true);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Poseidon")&&a==1)
        {
            character=24;
            story=12;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(false);
            PoseidonS.SetActive(true);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
        else if(g.Equals("Poseidon")&&a==2)
        {
            character=23;
            story=12;
            AthenaD.SetActive(false);
            AthenaS.SetActive(false);
            AresD.SetActive(false);
            AresS.SetActive(false);
            ApolloD.SetActive(false);
            ApolloS.SetActive(false);
            ArtemisD.SetActive(false);
            ArtemisS.SetActive(false);
            AphroditeD.SetActive(false);
            AphroditeS.SetActive(false);
            DemeterD.SetActive(false);
            DemeterS.SetActive(false);
            DionysusD.SetActive(false);
            DionysusS.SetActive(false);
            HermesD.SetActive(false);
            HermesS.SetActive(false);
            HeraD.SetActive(false);
            HeraS.SetActive(false);
            HephaestusD.SetActive(false);
            HephaestusS.SetActive(false);
            HadesD.SetActive(false);
            HadesS.SetActive(false);
            PoseidonD.SetActive(true);
            PoseidonS.SetActive(false);
            ZeusD.SetActive(false);
            ZeusS.SetActive(false);
        }
    }
}
